apiVersion: v1
kind: Service
metadata:
  labels:
    service: advertisementdb
  name: advertisementdb
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    service: advertisementdb
status:
  loadBalancer: {}
