apiVersion: v1
kind: Service
metadata:
  labels:
    service: advertisement
  name: advertisement
spec:
  ports:
  - name: "2226"
    port: 2226
    targetPort: 2226
  selector:
    service: advertisement
status:
  loadBalancer: {}
