apiVersion: v1
kind: Service
metadata:
  labels:
    service: cateringdb
  name: cateringdb
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    service: cateringdb
status:
  loadBalancer: {}
