version: '3'
services:
  zookeeper:
    container_name: 'zookeeper'
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"

  kafka:
    container_name: 'kafka'
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"

  mediadb:
    image: 'mongo'
    container_name: 'media_mongo_db'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    ports:
      - '27020:27017'
  scheduledb:
    image: mysql:5.7
    container_name: 'scheduledb'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduledb
    expose:
      - '3308'
    ports:
      - '3308:3306'
  ticketdb:
    image: mysql:5.7
    container_name: 'ticketdb'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketdb
    expose:
      - "3307"
    ports:
      - '3307:3306'
  halldb:
    image: 'mongo'
    container_name: 'halldb'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017:27017'

  media:
    container_name: 'media'
    image: 'docker.io/emielvandenbussche/media'
    links:
      - mediadb
    depends_on:
      - mediadb
    ports:
      - "2225:2225"
  gateway:
    container_name: 'gateway'
    image: 'docker.io/emielvandenbussche/gateway'
    links:
      - media
    depends_on:
      - media
    ports:
      - "3000:3000"
  schedule:
    container_name: 'schedule'
    image: 'docker.io/emielvandenbussche/schedule'
    links:
      - scheduledb
      - kafkabroker
      - zookeeper
    depends_on:
      - scheduledb
      - kafkabroker
      - zookeeper
    ports:
      - "2223:2223"
  hall:
    container_name: 'hall'
    image: 'docker.io/emielvandenbussche/hall'
    links:
      - halldb
      - kafkabroker
      - zookeeper
    depends_on:
      - halldb
      - kafkabroker
      - zookeeper
    ports:
      - "2221:2221"
  ticket:
    container_name: 'ticket'
    image: 'docker.io/emielvandenbussche/ticket'
    links:
      - ticketdb
      - kafkabroker
      - zookeeper
    depends_on:
      - ticketdb
      - kafkabroker
      - zookeeper
    ports:
      - "2222:2222"
