version: '3'
services:
  mediadb:
    image: 'mongo'
    container_name: 'media_mongo_db'
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    ports:
      - '27020:27017'

  media:
    container_name: 'media'
    image: 'docker.io/emielvandenbussche/media'
    links:
      - mediadb
    depends_on:
      - mediadb
    ports:
      - "2225:2225"
