apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: frontend
    spec:
      containers:
      - image: docker.io/emielvandenbussche/frontend:1.0
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
