apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
  name: gateway
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: gateway
status:
  loadBalancer: {}
