apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
  name: gateway
spec:
  ports:
  - name: "2225"
    port: 2225
    targetPort: 2225
  selector:
    service: gateway
status:
  loadBalancer: {}
