apiVersion: v1
kind: Service
metadata:
  labels:
    service: halldb
  name: halldb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: halldb
status:
  loadBalancer: {}
