apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: media
  name: media
spec:
  replicas: 1
  selector:
    matchLabels:
      service: media
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: media
    spec:
      containers:
      - image: docker.io/emielvandenbussche/media:2.0
        name: media
        ports:
        - containerPort: 2225
        resources: {}
      restartPolicy: Always
status: {}
