apiVersion: v1
kind: Service
metadata:
  labels:
    service: media
  name: media
spec:
  ports:
  - name: "2225"
    port: 2225
    targetPort: 2225
  selector:
    service: media
status:
  loadBalancer: {}
