apiVersion: v1
kind: Service
metadata:
  labels:
    service: mediadb
  name: mediadb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: mediadb
status:
  loadBalancer: {}
