apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mediadb
  name: mediadb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mediadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mediadb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo
        name: mediadb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
