apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mediadb
  name: mediadb
spec:
  ports:
  - name: "27020"
    port: 27020
    targetPort: 27017
  selector:
    io.kompose.service: mediadb
status:
  loadBalancer: {}
