apiVersion: v1
kind: Service
metadata:
  labels:
    service: scheduledb
  name: scheduledb
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    service: scheduledb
status:
  loadBalancer: {}
