apiVersion: v1
kind: Service
metadata:
  labels:
    service: statistics
  name: statistics
spec:
  ports:
  - name: "2228"
    port: 2228
    targetPort: 2228
  selector:
    service: statistics
status:
  loadBalancer: {}
