apiVersion: v1
kind: Service
metadata:
  labels:
    service: ticketdb
  name: ticketdb
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    service: ticketdb
status:
  loadBalancer: {}
